# Setup
title:               Ishan Mukherjee
tagline:             My personal website and blog
description:         Posts on science, books and more by <a href="https://twitter.com/ishanjmukherjee" target="_blank">@ishanjmukherjee</a>
url:                 http://ishanjmukherjee.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ishan Mukherjee
  url:               https://twitter.com/ishanjmukherjee
  email:             ishanmukherjee1234@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
